out = getArgument();
if (out == "") exit("Usage: <output-path>");
File.saveString("START\n", out);

newImage("jit-input.tif", "8-bit black", 4, 3, 2);
run("Properties...", "channels=2 slices=1 frames=1");
File.append("FIXTURE READY\n", out);
Stack.setChannel(1); setPixel(0, 0, 7);
Stack.setChannel(2); setPixel(0, 0, 19);
originalId = getImageID();
originalTitle = getTitle();

sourceCopyTitle = "__aNMJ_source_" + originalId;
run("Duplicate...", "title=[" + sourceCopyTitle + "] duplicate");
sourceCopyId = getImageID();
File.append("SOURCE COPY READY\n", out);
selectImage(sourceCopyId);
templateTitle = "__aNMJ_template_" + sourceCopyId;
run("Duplicate...", "title=[" + templateTitle + "] duplicate");
templateId = getImageID();
File.append("TEMPLATE COPY READY\n", out);

selectImage(originalId);
File.append("BEFORE ORIGINAL ARRANGE\n", out);
run("Arrange Channels...", "new=12");
arrangedOriginalId = getImageID();
File.append("AFTER ORIGINAL ARRANGE original=" + originalId + " arranged=" + arrangedOriginalId + "\n", out);
File.append("BEFORE ORIGINAL STACK C1\n", out);
Stack.setChannel(1);
File.append("AFTER ORIGINAL STACK C1\n", out);
File.append("BEFORE ORIGINAL JAVA SPLIT\n", out);
status = call("io.github.alzeiby.anmjmorphplus.EarlySplitChannelsBridge.splitCurrent");
File.append("AFTER ORIGINAL JAVA SPLIT " + status + "\n", out);
statusParts = split(status, ";");
if (statusParts.length != 3 || statusParts[0] != "OK") exit("Original Java Split Channels failed: " + status);
if (isOpen(arrangedOriginalId)) exit("Original post-Arrange source remained open after split");
if (getTitle() != "C2-" + originalTitle) exit("Original split did not leave C2 current");
originalC2Id = getImageID();
if (!isOpen("C1-" + originalTitle)) exit("Original C1 output missing");
safeC1 = "C1-" + originalTitle;
selectWindow(safeC1); originalC1Id = getImageID();
selectImage(originalC2Id);
if (statusParts[1] != "" + originalC1Id || statusParts[2] != "" + originalC2Id) exit("Original bridge returned wrong C1/C2 IDs");
if (!isOpen(sourceCopyId)) exit("Original split modified sourceCopy");
if (!isOpen(templateId)) exit("Original split modified template copy");
File.append("ORIGINAL|arranged=" + arrangedOriginalId + "|C1=" + originalC1Id + "|C2=" + originalC2Id + "|current=" + getImageID() + "|sourceCopy=" + sourceCopyId + "\n", out);

selectImage(templateId);
File.append("BEFORE TEMPLATE ARRANGE\n", out);
run("Arrange Channels...", "new=12");
arrangedTemplateId = getImageID();
File.append("AFTER TEMPLATE ARRANGE template=" + templateId + " arranged=" + arrangedTemplateId + "\n", out);
File.append("BEFORE TEMPLATE STACK C1\n", out);
Stack.setChannel(1);
File.append("AFTER TEMPLATE STACK C1\n", out);
File.append("BEFORE TEMPLATE JAVA SPLIT\n", out);
status = call("io.github.alzeiby.anmjmorphplus.EarlySplitChannelsBridge.splitCurrent");
File.append("AFTER TEMPLATE JAVA SPLIT " + status + "\n", out);
statusParts = split(status, ";");
if (statusParts.length != 3 || statusParts[0] != "OK") exit("Template Java Split Channels failed: " + status);
if (isOpen(arrangedTemplateId)) exit("Template post-Arrange source remained open after split");
if (getTitle() != "C2-" + templateTitle) exit("Template split did not leave C2 current");
templateC2Id = getImageID();
if (!isOpen("C1-" + templateTitle)) exit("Template C1 output missing");
selectWindow("C1-" + templateTitle); templateC1Id = getImageID();
selectImage(templateC2Id);
if (statusParts[1] != "" + templateC1Id || statusParts[2] != "" + templateC2Id) exit("Template bridge returned wrong C1/C2 IDs");
if (!isOpen(sourceCopyId)) exit("Template split modified sourceCopy");
if (!isOpen(originalC1Id) || !isOpen(originalC2Id)) exit("Template split modified original split outputs");
File.append("TEMPLATE|arranged=" + arrangedTemplateId + "|C1=" + templateC1Id + "|C2=" + templateC2Id + "|current=" + getImageID() + "|sourceCopy=" + sourceCopyId + "\n", out);

newImage("jit-invalid-one-channel", "8-bit black", 2, 2, 1);
status = call("io.github.alzeiby.anmjmorphplus.EarlySplitChannelsBridge.splitCurrent");
if (!startsWith(status, "ERROR: ")) exit("Java Split Channels failure did not fail closed: " + status);
File.append("FAIL-CLOSED|" + status + "\n", out);

run("Close All");
File.append("DONE split channels jit\n", out);
run("Quit");
